# Generated by Django 5.2 on 2025-04-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(help_text='Berat badan dalam kg')),
                ('height', models.FloatField(help_text='Tinggi badan dalam cm')),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10)),
                ('age', models.IntegerField(help_text='Usia dalam tahun')),
                ('water_intake', models.IntegerField(help_text='Asupan air dalam ml')),
                ('sport_frequency', models.FloatField(help_text='Frekuensi olahraga (1.2-1.9)')),
                ('smoke_frequency', models.IntegerField(help_text='Jumlah rokok per hari')),
                ('stress_level', models.IntegerField(help_text='Tingkat stres (1-10)')),
                ('alcohol_frequency', models.IntegerField(help_text='Jumlah minum alkohol per minggu')),
                ('daily_calories', models.IntegerField(help_text='Asupan kalori harian')),
                ('sleep_amount', models.FloatField(help_text='Jumlah tidur dalam jam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kuesioner Harian',
                'verbose_name_plural': 'Kuesioner Harian',
                'ordering': ['-date'],
            },
        ),
    ]
