# Generated by Django 5.2 on 2025-04-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('kuesioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquestionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.pengguna'),
        ),
    ]
