# Generated by Django 5.2 on 2025-04-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to='authorization.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='normal', serialize=False, to='authorization.pengguna')),
                ('nama_depan', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_belakang', models.CharField(blank=True, max_length=255, null=True)),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('tinggi_badan', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('umur', models.IntegerField(blank=True, null=True)),
                ('poin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
