# Generated by Django 5.1.1 on 2025-04-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_permission_role_pengguna_role_role_permission'),
        ('authorization', '0003_add_permissions'),
    ]

    operations = [
    ]
