# Generated by Django 5.1.1 on 2025-04-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_merge_20250413_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=50)),
                ('last_verified_counter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_device', to='authorization.pengguna')),
            ],
        ),
    ]
